### ISSUE TITLE
UI建议

### ISSUE THREAD

**Issue by SuiYunsy** [october-coder/api-check#11]
1. 右侧的通知不必每次打开都弹出，可以记录用户是否是点击过x/程序是否有更新，点过x下一次打开就不弹出，程序有更新再弹出。
2. 输入框padding可能需要再大一点，否则下划线看不到，如图：
```
api_check.com
sk-66_000_sdf_sdf_
```
![image](https://github.com/user-attachments/assets/5046bed6-57fe-4b9c-8872-1925413782e7)

**Comment by rickcert** [comment]
输入框paddin 下划线看不到 这个mac 和ios 没有复现出来

**Comment by SuiYunsy** [comment]
抱歉，没有做严谨的测试，并非padding的问题。

用安卓设备和家里的笔记本再测了一下。安卓的也有类似问题但不明显，下面这张是家里笔记本测得：

![image](https://github.com/user-attachments/assets/eb0d7c3a-66c1-4c2c-9d61-0171da8ecde8)

目前可以确定，因设备、系统、字体以及各种设置的原因，总有兼容性问题。

最简单的解决办法是往 global.css 写入
```css
input {
  line-height: normal !important;
}
```

本地 vite 测试验证通过：

![image](https://github.com/user-attachments/assets/aa20136a-e64d-479d-9c6b-5ab7e0b3df60)
