### ISSUE TITLE
请求对于openai apikey的余额查询

### ISSUE THREAD

**Issue by Payne-Wang** [october-coder/api-check#5]
从[这个项目]( https://api.openai.com/v1/dashboard/activity?end_date=2024-02-01&start_date=2024-01-01)得知一些隐藏接口：
账号订阅的情况（通过sees）：https://api.openai.com/v1/dashboard/billing/subscription
用量清单（通过sees）：https://api.openai.com/v1/dashboard/billing/usage?start_date=2023-12-1&end_date=2023-12-12
指定日期用量情况（通过key）：https://api.openai.com/v1/usage?date=2023-12-1&user_public_id=user-xxx
用量明细接口：https://api.openai.com/v1/dashboard/activity?end_date=2024-02-01&start_date=2024-01-01

不知能否加入进去以提供对openai key的余额查询？它的这个项目文件已经无法使用，但他们自己部署的网站可用（估计代码闭源了），而且上述接口都只支持sees-XXX，不支持sk-XXX，但是他们自己部署的网站却可以用sk-XXX，可能还存在sk转sees的接口？

谢谢大佬！

**Comment by QAbot-zh** [comment]
嗯这些接口是知道的，oneapi、newapi 也是继承这几个最早的查询接口的，openai 后来改成只能在网页查询（即sess查询）后sk-xx 查询接口就废了，之前 pandora 项目还能提供登录接口抓取 sess，现在也不开放了。暂时应该是没法支持上了。

**Comment by Payne-Wang** [comment]
> 嗯这些接口是知道的，oneapi、newapi 也是继承这几个最早的查询接口的，openai 后来改成只能在网页查询（即sess查询）后sk-xx 查询接口就废了，之前 pandora 项目还能提供登录接口抓取 sess，现在也不开放了。暂时应该是没法支持上了。

谢谢回复。
不过上面那个人的项目中，他自己部署了一下，我测试了一下，发现是可以直接使用sk获取使用额度的，不知道咋实现的。难道还有sk转sess的接口？
链接(含广告):https://gptbill.lonlie.cn/

**Comment by QAbot-zh** [comment]
> > 嗯这些接口是知道的，oneapi、newapi 也是继承这几个最早的查询接口的，openai 后来改成只能在网页查询（即sess查询）后sk-xx 查询接口就废了，之前 pandora 项目还能提供登录接口抓取 sess，现在也不开放了。暂时应该是没法支持上了。
> 
> 谢谢回复。 不过上面那个人的项目中，他自己部署了一下，我测试了一下，发现是可以直接使用sk获取使用额度的，不知道咋实现的。难道还有sk转sess的接口？ 链接(含广告):https://gptbill.lonlie.cn/

它这个也相当于是中转，跟 oneapi、newapi 原理类似的
