### ISSUE TITLE
o1无法进行温度验证和官转验证

### ISSUE THREAD

**Issue by wang0yue** [october-coder/api-check#7]
温度验证：该次调用响应异常
官转验证：400
应该是请求体参数多了

**Comment by wang0yue** [comment]
如果不传温度参数，序列推理也许也能一定程度反映真假？

**Comment by QAbot-zh** [comment]
目前是加了 reasoning_tokens 的判断，只有正规 api 会带这个推理参数

![image](https://github.com/user-attachments/assets/a7c86ca9-0347-44bf-9403-29ce5c19bcfb)
